canvas = document.getElementById("myCanvas");
abc= canvas.getContext("2d");
abc.beginPath();
abc.strokeStyle = "grey";
abc.lineWidth = 4;
abc.rect(150, 140 , 500 , 250);
abc.stroke();

abc.beginPath();
abc.strokeStyle = "blue";
abc.lineWidth = 5;
abc.arc(250, 200, 40 ,0 , 2*Math.PI);
abc.stroke();
abc.beginPath();
abc.strokeStyle = "black";
abc.lineWidth = 5;
abc.arc(350, 200, 40 ,0 , 2*Math.PI);
abc.stroke();
abc.beginPath();
abc.strokeStyle = "red";
abc.lineWidth = 5;
abc.arc(450, 200, 40 ,0 , 2*Math.PI);
abc.stroke();
abc.beginPath();
abc.strokeStyle = "orange";
abc.lineWidth = 5;
abc.arc(300, 240, 40 ,0 , 2*Math.PI);
abc.stroke();
abc.beginPath();
abc.strokeStyle = "green";
abc.lineWidth = 5;
abc.arc(400, 240, 40 ,0 , 2*Math.PI);
abc.stroke();